### ISSUE TITLE
Can't see added tasks

### ISSUE THREAD

**Issue by yarikbratashchuk** [wezm/leaf#9]
I can't see my tasks (sorry for this poor gif):
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12980380/86279079-1eaeda00-bbe2-11ea-9cc7-86442c653cdf.gif)
What did I miss this time?

**Comment by yarikbratashchuk** [comment]
The issue what that I used `~` in `LEAF_TASKS_PATH`. Everything works. Thanks:)

**Comment by wezm** [comment]
🤔 Hmm yes `~` doesn't get expanded in environment variables. It's customary to do something like `LEAF_TASKS_PATH=$HOME` in that case. I'll leave this open with the intent to add a note to the README.

- [x] Add note to README about how to refer to home directory in `LEAF_TASKS_PATH`.
